#PBS -N HW02
#PBS -l nodes=1:ppn=16
#PBS -l walltime=5:00
#PBS -q coc-ice
#PBS -oe result.out

cd $PBS_O_WORKDIR
module purge 
module load gcc
module load mvapich2/2.3.2

make clean
make

export Insub="input_"
export Outsub="output_"
export Endsub=".txt"
for p in {5..7}; do
  for n in 8 20; do
    inFile="${Insub}${n}${Endsub}"
    outFile="${Outsub}${n}_${p}${Endsub}"
    mpirun -np ${p} ./pqsort "${inFile}" "${outFile}"
  done
done